---
title: "R Notebook"
output: html_notebook
---


```{r}
library(utils)
setwd("C:/Users/Brandon/Documents/Strategy_Paper_SHP")
otimeout <- getOption("timeout")
options(timeout=1200)
# TODO: There is probably a better source. Extract from 3GB Inegi census?
#download.file("https://pautas.ine.mx/transparencia/mapas/cob_2020/SECCION.zip","SECCION2.zip")
#options(timeout=otimeout)
#unzip("SECCION2.zip")

```



```{r}
library("sf")
seccion_base.sf <- read_sf("C:/Users/Brandon/Documents/Strategy_Paper_SHP/2017_07_test/07/SECCION.shp", check_ring_dir=TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
library(ggplot2)

i<-2
 

seccion_base.sf %>% filter(entidad==planFull.df[[i,"edon"]]) %>% 
  left_join(planFull.df[[i,"plan"]][[1]],by=c("seccion")) %>% mutate(district=factor(district)) %>%
  ggplot() + aes(fill=district) + geom_sf()


```

```{r}
j<-3  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planFull.df[[i,"plan"]][[1]],planFull.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planFull.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
```
```{r}
i<-2 ; j <- 3
plan_1.tbl <- planFull.df[[i,"plan"]][[1]]
plan_2.tbl <- planFull.df[[j,"plan"]][[1]]

dis_1.tbl <- plan_1.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))
dis_2.tbl <- plan_2.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))

#example of calculating size differences between two different districts, without assuming numbering is the same
intersect(dis_1.tbl[1,"seclist"][[1]][[1]],dis_2.tbl[1,"seclist"][[1]][[1]])
```


###STATE BY STATE ANALYSIS
###Comparing Algorithm Plans + Winning Plans 2013 vs. 2017

#1
#Algorithm Plans
```{r}
i<-51
 

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(planProcessing.df[[i,"plan"]][[1]],by=c("seccion")) %>% mutate(district=factor(district)) %>%
  ggplot() + aes(fill=district) + geom_sf()

```
```{r}
j<-9  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
i<-51 ; j <- 9
plan_1.tbl <- planFull.df[[i,"plan"]][[1]]
plan_2.tbl <- planFull.df[[j,"plan"]][[1]]

dis_1.tbl <- plan_1.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))
dis_2.tbl <- plan_2.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))

#example of calculating size differences between two different districts, without assuming numbering is the same
intersect(dis_1.tbl[1,"seclist"][[1]][[1]],dis_2.tbl[1,"seclist"][[1]][[1]])
```
#Winning Plans
```{r}
i<-50
 

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(planProcessing.df[[i,"plan"]][[1]],by=c("seccion")) %>% mutate(district=factor(district)) %>%
  ggplot() + aes(fill=district) + geom_sf()

```
```{r}
j<-9  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
i<-50 ; j <-9
plan_1.tbl <- planFull.df[[i,"plan"]][[1]]
plan_2.tbl <- planFull.df[[j,"plan"]][[1]]

dis_1.tbl <- plan_1.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))
dis_2.tbl <- plan_2.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))

#example of calculating size differences between two different districts, without assuming numbering is the same
intersect(dis_1.tbl[1,"seclist"][[1]][[1]],dis_2.tbl[1,"seclist"][[1]][[1]])
```
#2
#Algorithm
```{r}
i<-83
 

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(planProcessing.df[[i,"plan"]][[1]],by=c("seccion")) %>% mutate(district=factor(district)) %>%
  ggplot() + aes(fill=district) + geom_sf()

```
```{r}
j<-27  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
i<-83 ; j <-27
plan_1.tbl <- planFull.df[[i,"plan"]][[1]]
plan_2.tbl <- planFull.df[[j,"plan"]][[1]]

dis_1.tbl <- plan_1.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))
dis_2.tbl <- plan_2.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))

#example of calculating size differences between two different districts, without assuming numbering is the same
intersect(dis_1.tbl[1,"seclist"][[1]][[1]],dis_2.tbl[1,"seclist"][[1]][[1]])
```
#Winning
```{r}
i<-69
 

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(planProcessing.df[[i,"plan"]][[1]],by=c("seccion")) %>% mutate(district=factor(district)) %>%
  ggplot() + aes(fill=district) + geom_sf()

```
```{r}
j<-161  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
i<-69 ; j <- 161
plan_1.tbl <- planFull.df[[i,"plan"]][[1]]
plan_2.tbl <- planFull.df[[j,"plan"]][[1]]

dis_1.tbl <- plan_1.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))
dis_2.tbl <- plan_2.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))

#example of calculating size differences between two different districts, without assuming numbering is the same
intersect(dis_1.tbl[1,"seclist"][[1]][[1]],dis_2.tbl[1,"seclist"][[1]][[1]])
```



#3
#Algorithm
```{r}
i<-347
 

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(planProcessing.df[[i,"plan"]][[1]],by=c("seccion")) %>% mutate(district=factor(district)) %>%
  ggplot() + aes(fill=district) + geom_sf()

```
```{r}
j<-162  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
i<-347 ; j <- 162
plan_1.tbl <- planFull.df[[i,"plan"]][[1]]
plan_2.tbl <- planFull.df[[j,"plan"]][[1]]

dis_1.tbl <- plan_1.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))
dis_2.tbl <- plan_2.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))

#example of calculating size differences between two different districts, without assuming numbering is the same
intersect(dis_1.tbl[1,"seclist"][[1]][[1]],dis_2.tbl[1,"seclist"][[1]][[1]])
```
#Winning
```{r}
i<-348
 

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(planProcessing.df[[i,"plan"]][[1]],by=c("seccion")) %>% mutate(district=factor(district)) %>%
  ggplot() + aes(fill=district) + geom_sf()

```
```{r}
j<-149  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
i<-348 ; j <- 149
plan_1.tbl <- planFull.df[[i,"plan"]][[1]]
plan_2.tbl <- planFull.df[[j,"plan"]][[1]]

dis_1.tbl <- plan_1.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))
dis_2.tbl <- plan_2.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))

#example of calculating size differences between two different districts, without assuming numbering is the same
intersect(dis_1.tbl[1,"seclist"][[1]][[1]],dis_2.tbl[1,"seclist"][[1]][[1]])
```

#7
#winning different from Algorithm
```{r}
i<-118
 

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(planProcessing.df[[i,"plan"]][[1]],by=c("seccion")) %>% mutate(district=factor(district)) %>%
  ggplot() + aes(fill=district) + geom_sf()

```
```{r}
j<-113  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
i<-118 ; j <- 113
plan_1.tbl <- planFull.df[[i,"plan"]][[1]]
plan_2.tbl <- planFull.df[[j,"plan"]][[1]]

dis_1.tbl <- plan_1.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))
dis_2.tbl <- plan_2.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))

#example of calculating size differences between two different districts, without assuming numbering is the same
intersect(dis_1.tbl[1,"seclist"][[1]][[1]],dis_2.tbl[1,"seclist"][[1]][[1]])
```


#15
```{r}
i<-314
 

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(planProcessing.df[[i,"plan"]][[1]],by=c("seccion")) %>% mutate(district=factor(district)) %>%
  ggplot() + aes(fill=district) + geom_sf()

```
```{r}
j<-149  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
i<-314 ; j <- 149
plan_1.tbl <- planFull.df[[i,"plan"]][[1]]
plan_2.tbl <- planFull.df[[j,"plan"]][[1]]

dis_1.tbl <- plan_1.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))
dis_2.tbl <- plan_2.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))

#example of calculating size differences between two different districts, without assuming numbering is the same
intersect(dis_1.tbl[1,"seclist"][[1]][[1]],dis_2.tbl[1,"seclist"][[1]][[1]])
```
#### Academic Maps

```{r}
Academic_maps <- planProcessing.df %>%
  filter(planid == "42.41505-15-2013" | planid =="academic-pri-A" | planid == "academic-pri-emmPobOk" | planid == "academic-pri-ericMagarPobOk" | planid == "academic-pri-pedro.esquivel.v1")
```

```{r}
i<-305
 

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(planProcessing.df[[i,"plan"]][[1]],by=c("seccion")) %>% mutate(district=factor(district)) %>%
  ggplot() + aes(fill=district) + geom_sf()


```
#Academic-Pri-A
```{r}
j<-1  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
i<-305 ; j <- 3
plan_1.tbl <- planFull.df[[i,"plan"]][[1]]
plan_2.tbl <- planFull.df[[j,"plan"]][[1]]

dis_1.tbl <- plan_1.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))
dis_2.tbl <- plan_2.tbl %>% group_by(district) %>% summarize(seclist=list(seccion))

#example of calculating size differences between two different districts, without assuming numbering is the same
intersect(dis_1.tbl[1,"seclist"][[1]][[1]],dis_2.tbl[1,"seclist"][[1]][[1]])
```
Academic-Pri-emmpobok
```{r}
j<-2  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
```
Academic-pri-ericmagarpobok
```{r}
j<-3  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
```

Academic-pri-pedro.esquivel.v1
```{r}
j<-4  # this has the same edon -- otherwise it ain't comparable :-)

# assumes plans have same district numbering order -- TODO: reorder district numbers for best match before differencing
dcomp<- full_join(planProcessing.df[[i,"plan"]][[1]],planProcessing.df[[j,"plan"]][[1]],by=c("seccion")) %>% mutate(district.diff=district.x==district.y)

seccion_base.sf %>% filter(entidad==planProcessing.df[[i,"edon"]]) %>% 
  left_join(dcomp,by=c("seccion"))  %>%
  ggplot() + aes(fill=district.diff) + geom_sf()
```


```{r}
plan1 <- planProcessing.df[[119,"plan"]][[1]] 
plan2 <- planProcessing.df[[1,"plan"]][[1]] 



tmp %>% filter(!str_detect(planid,"base")) %>% 
  group_by(edon) %>% 
  summarise(mean(base_diff_percent),base_diff_delta=mean(base_diff_delta))

tmp %>% 
  filter(edon %in% c(2,15)) %>% 
  rowwise() %>% 
  mutate(ndists = length(na.omit(unique(plan$district)))) %>% 
  select(planid,edon,ndists)

# compare each plan to baseline
# compare to algorithm plan
# compare to prior proposal
#TODO: academic- districts and 13.74065-2-2013	have wrong number of dists

```

